### ISSUE TITLE
Node v4.2.1 support

### ISSUE THREAD

**Issue by dmtrs** [bnoordhuis/node-backtrace#2]
Hello there, 
Is there any plan for Node v4.2.1 support of this tool. I am trying to use it and get:

```
cktrace@0.0.1 install /Users/dmtrs/code/node-backtrace
> node-gyp rebuild
>
>   CXX(target) Release/obj.target/backtrace/backtrace.o

  ../backtrace.cc:65:39: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> backtrace(const v8::Arguments&);
                                      ^~~~~~~~~~~~~
                                      v8::internal::Arguments
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../backtrace.cc:92:41: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
              v8::FunctionTemplate::New(backtrace)->GetFunction());
                                        ^~~~~~~~~
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:4350:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../backtrace.cc:91:27: error: no member named 'New' in 'v8::String'
  module->Set(v8::String::New("backtrace"),
              ~~~~~~~~~~~~^
../backtrace.cc:113:39: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> backtrace(const v8::Arguments&)
                                      ^~~~~~~~~~~~~
                                      v8::internal::Arguments
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../backtrace.cc:116:24: error: too few arguments to function call, single argument 'isolate' was not specified
  return v8::Undefined();
         ~~~~~~~~~~~~~ ^
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:315:3: note: 'Undefined' declared here
  friend Local<Primitive> Undefined(Isolate* isolate);
  ^
../backtrace.cc:177:13: error: no member named 'SetJitCodeEventHandler' in 'v8::V8'
    v8::V8::SetJitCodeEventHandler(v8::kJitCodeEventEnumExisting,
    ~~~~~~~~^
../backtrace.cc:179:13: error: no member named 'SetJitCodeEventHandler' in 'v8::V8'
    v8::V8::SetJitCodeEventHandler(v8::kJitCodeEventDefault, NULL);
    ~~~~~~~~^
../backtrace.cc:180:55: error: too few arguments to function call, expected at least 2, have 1
    stack_trace = v8::StackTrace::CurrentStackTrace(64);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:1555:3: note: 'CurrentStackTrace' declared here
  static Local<StackTrace> CurrentStackTrace(
  ^
/Users/dmtrs/.node-gyp/4.2.1/include/node/v8.h:327:9: error: cannot initialize a member subobject of type 'v8::FunctionTemplate *' with an lvalue of type 'const char *'
      : val_(that) {}
        ^    ~~~~
../backtrace.cc:91:31: note: in instantiation of function template specialization 'v8::Local<v8::FunctionTemplate>::Local<const char>' requested here
  module->Set(v8::String::New("backtrace"),
                              ^
9 errors generated.
make: *** [Release/obj.target/backtrace/backtrace.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dmtrs/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/dmtrs/.nvm/versions/node/v4.2.1/bin/node" "/Users/dmtrs/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dmtrs/code/node-backtrace
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/dmtrs/.nvm/versions/node/v4.2.1/bin/node" "/Users/dmtrs/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! backtrace@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backtrace@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the backtrace package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls backtrace
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmtrs/code/node-backtrace/npm-debug.log

```

**Comment by loretoparisi** [comment]
I get an error

``` shell
../hello.cc:4:10: fatal error: 'compat-inl.h' file not found
```

**Comment by bnoordhuis** [comment]
@loretoparisi That looks unrelated.  There is no hello.cc in the repository.
